# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java-docker
      context: .
  googleCloudBuild:
    diskSizeGb: 100
    machineType: N1_HIGHCPU_8
    timeout: 900s
test:
  - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java-docker
    structureTests:
      - './structure-tests/*'
# defines the Kubernetes manifests to deploy on each run
deploy:
  # kpt:
  #   dir: kpt-hello
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: jib
  build:
    artifacts:
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        fromImage: openjdk:11-jre-slim
        args:
        - -Dmaven.test.skip=true  
- name: dockerfile
  build:
    artifacts:
      - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java-docker
        context: .
    local: {}
- name: buildpack
  build:
    artifacts:
      - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java-buildpack
        buildpacks: 
          builder: "gcr.io/buildpacks/builder:v1"
    local: {}
    # googleCloudBuild: {}