steps:
- id: 'deploy image'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials ${_GKE_CLUSTER} --project ${_GKE_PROJECT} --zone ${_GKE_ZONE}
    kubectl get nodes
substitutions:
  _IMAGE_PATH: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java-docker
  _COSIGN_PASSWORD: 'VMware1!'
  _RESULT_PATH: /workspace/result.json
  _GKE_CLUSTER: tsmc
  _GKE_ZONE: asia-east1-a
  _GKE_PROJECT: shawn-demo-2022
  