steps:
- id: 'buildImage'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    skaffold build --file-output tags.json
- id: 'sign image'
  name: 'gcr.io/shawn-demo-2022/cosign'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    ImageDigest="$(gcloud container images list-tags --format='get(digest)' ${_IMAGE_PATH} | head -1)"
    ImageToAttest="${_IMAGE_PATH}@${ImageDigest}"
    export COSIGN_PASSWORD=${_COSIGN_PASSWORD}
    gsutil cp gs://shawn-demo-2022/keys/cosign-1.key ./cosign.key
    gsutil cp gs://shawn-demo-2022/attestations/in-toto-simple.template ./in-toto-simple.template
    cosign attest --key ./cosign.key --predicate ./in-toto-simple.template ${ImageToAttest}
- id: 'verify image'
  name: 'gcr.io/shawn-demo-2022/cosign'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    ImageDigest="$(gcloud container images list-tags --format='get(digest)' ${_IMAGE_PATH} | head -1)"
    ImageToAttest="${_IMAGE_PATH}@${ImageDigest}"
    gsutil cp gs://shawn-demo-2022/keys/cosign-1.pub ./cosign.pub
    gsutil cp gs://shawn-demo-2022/attestations/policy.rego ./policy.rego
    cosign verify-attestation --key cosign-1.pub --policy policy.rego ${ImageToAttest}    
substitutions:
  _IMAGE_PATH: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java
  _COSIGN_PASSWORD: 'VMware1!'
  